App05/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# Create database object
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    # REQUIRED for session, login, flash
    app.config['SECRET_KEY'] = 'your-secret-key'

    # Database configuration
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///todo.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # initialize db
    db.init_app(app)

    # Import blueprints
    from app.routes.auth import auth_bp
    from app.routes.task import task_bp   

    # Register blueprints
    app.register_blueprint(auth_bp)
    app.register_blueprint(task_bp)

    return app

App05/app/routes/auth.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, session

auth_bp = Blueprint('auth', __name__)

USER_CREDENTIALS= {
    'username' : 'admin',
    'password' : '1234'
}

@auth_bp.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if username == USER_CREDENTIALS['username'] and password == USER_CREDENTIALS['password'] :
            session['user'] = username
            flash("Login successful", 'success')
        else:
            flash("invaild username or password")
    return render_template("login.html")

@auth_bp.route("/logout")
def logout():
    session.pop('user', None)
    flash("logout successfuly", "info")
    return redirect(url_for("auth.login"))

App05/app/routes/task.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, session
from app import db
from app.model import Task

task_bp = Blueprint("tasks", __name__)

@task_bp.route("/")
def view_tasks():
    if 'user' not in session:
        return redirect(url_for("auth.login"))

    tasks = Task.query.all()
    return render_template("task.html", tasks=tasks)


@task_bp.route("/add", methods=["POST"])
def add_task():
    if 'user' not in session:
        return redirect(url_for("auth.login"))

    title = request.form.get("title")

    if title:
        new_task = Task(title=title, status="Pending")
        db.session.add(new_task)
        db.session.commit()
        flash("Task added successfully", "success")

    return redirect(url_for("tasks.view_tasks"))


@task_bp.route("/toggle/<int:task_id>", methods=["POST"])
def toggle_status(task_id):
    task = Task.query.get(task_id)

    if task:
        if task.status == "Pending":
            task.status = "Working"
        elif task.status == "Working":
            task.status = "Done"
        else:
            task.status = "Pending"

        db.session.commit()

    return redirect(url_for("tasks.view_tasks"))


@task_bp.route("/clear", methods=["POST"])
def clear_task():
    Task.query.delete()
    db.session.commit()
    flash("All tasks are cleared!!", "info")
    return redirect(url_for("tasks.view_tasks"))

App05/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} To-do App  {% endblock %} </title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" >
</head>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
<body>
    <header>
        <div class="continer">
            <h2>My To-do App</h2>
            <nav>
                <a href="{{url_for('tasks.view_tasks')}}">Home</a>
                {% if 'user' in session %}
                    <a href="{{url_for('auth.logout')}}">Logout</a>
                {% else %}
                    <a href="{{url_for('auth.login')}}">Login</a>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="continer">
        {% with messages = get_flashed_messages(with_categories = True) %}
            {% for category, message in messages %}
                <div class="flash {{category}} ">{{message}} </div>
            {% endfor %}

        {% endwith %}

    {% block content %}{% endblock %}

    </main>

    <footer>
        <div class="footer">
            <p>&copy; 2025 My Flask Todo-App </p>
        </div>
    </footer>


    
</body>
</html>

App05/app/templates/login.html
{% extends "base.html" %} 
{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="login-box">
        <h2>Login</h2>
        <form  method="post">
            <div class="form-gourp">
                <label for="username">Username</label>
                <input type="text" name="username" id="username" required >

            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required >
            </div>
            <button type="submit" class="btn" >Login </button>
        </form>
    </div>
{% endblock %}

App05/app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<p>registertion Comming soon</p>
    
{% endblock %}

App05/app/templates/task.html
{% extends "base.html" %} 
{% block title %}
    Tasks
{% endblock %}

{% block content %}
    <div class="task-box">
        <h2>Your Tasks</h2>
        <form action="{{url_for('tasks.add_task')}}" method="post" class="task-form" >
            <input type="text" name="title" placeholder="New task" required>
            <button type="submit" class="btn" >Add</button>

        </form>
        {% if tasks %}
            <form action="{{url_for('tasks.clear_task')}}" method="post"  ></form>
            <button type="submit" class="btn clear-btn " >Clear all tasks</button>
        
        <br>

        <table>
            <thead>
                <tr>
                    <th>Tasks</th>
                    <th>Status</th>
                    <th>Change</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td>{{loop.index}}</td>
                        <td>{{loop.title}}</td>
                        <td>
                            <span class=" badge {{ task.status|lower }}" > {{task.status}} </span>
                        </td>
                        <td>
                            <form action="{{url_for('tasks.toggle_status', task_id=task.id )}}" method="post">
                                <button type="submit" class="small-btn" >Next</button>
                            </form>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <p>No tasks add yet....</p>

        {% endif %}

        
    </div>
{% endblock %}